# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/tutorial/Nexys4DDR_Master.xdc

# IP: ip/clk_5MHZ/clk_5MHZ.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_5MHZ || ORIG_REF_NAME==clk_5MHZ} -quiet] -quiet
