webtalk_init -webtalk_dir C:/Users/a/Desktop/Vivado_Project_chh/Project/2019-01-23/StopWatch/StopWatch.sim/sim_1/behav/xsim/xsim.dir/seven_display_tb_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 25 15:36:25 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "57d02d3c-4210-4467-a3e5-cf8fc480d069" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "81bb8c3c6b564381afd30f5f0e47337e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "9" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "549 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "32 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "258" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "13" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.34_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "114224_KB" -context "xsim\\usage"
webtalk_transmit -clientid 62159469 -regid "" -xml C:/Users/a/Desktop/Vivado_Project_chh/Project/2019-01-23/StopWatch/StopWatch.sim/sim_1/behav/xsim/xsim.dir/seven_display_tb_top_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/a/Desktop/Vivado_Project_chh/Project/2019-01-23/StopWatch/StopWatch.sim/sim_1/behav/xsim/xsim.dir/seven_display_tb_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/a/Desktop/Vivado_Project_chh/Project/2019-01-23/StopWatch/StopWatch.sim/sim_1/behav/xsim/xsim.dir/seven_display_tb_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
